### PR TITLE
Added methods for work with grid system

### PR DESCRIPTION
**Pull request by irpsv**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
Hmm. What's the use case for it? To me these are direct wrappers for HTML tags which could be used directly w/o any issues.

**Comment by irpsv** [comment]
For simplicity.
Usual way:
```html
<div class='container'>
	<div class='row'>
		<div class='col-xs-12 col-sm-4'>
			filter of list
		</div>
		<div class='col-xs-12 col-sm-8'>
			list items
		</div>
	</div>
</div>
```
With using `Html::grid`:
```php
<div class='container'>
	<?= Html::grid(
		[
			"xs" => [12,12],
			"sm" => [4,8]
		],
		[
			"filter of list",
			"list items"
		]
	)?>
</div>
```
I think, second way easier.

**Comment by samdark** [comment]
I think it's different but definitely isn't easier.

**Comment by samdark** [comment]
The con here is that you're forcing developers to learn another syntax besides what they already know about bootstrap. Pros aren't clear since it's compare-able in the number of chars typed and, as to me, readability is reduced.

Won't accept the proposal. Sorry and thanks for trying.

**Pull request closed without merging**
