### PR TITLE
Fixes #96, fixes #157: Fix active status of multilevel submenu items

### LINKED ISSUE #96: add active class into li > dropdown
Yii2 don't added the class active into li > dropdown ....

don't add this active class when a children of the dropdown is active,
if some children of the dropdown is active, into dropdown Yii2 must to added this class, but don't work, i added this class how you can see at pic

screenshot_3

### LINKED ISSUE #157: Submenu items are not marked as active properly
Currently `Nav` class supports setting `items` property specifying multi-level submenus but this is not taken into account when determining active status of child items of submenus (submenu `<li>` elements do not receive `active` class).

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | to be done
| Fixed issues  | https://github.com/yiisoft/yii2-bootstrap/issues/96, https://github.com/yiisoft/yii2-bootstrap/issues/157

### CODE REVIEW

**Comment by PowerGamer1** [comment]
Please add the following `if` at the start of the `foreach` to skip pointless processing of invisible menu items (I can't modify this pull request myself since you created your own based on my original patch):
```PHP
    protected function isChildActive($items, &$active)
    {
        foreach ($items as $i => $child) { // <-- add this if
            if (is_array($child) && !ArrayHelper::getValue($child, 'visible', true)) {
                continue;
            }
            if (ArrayHelper::remove($items[$i], 'active', false) || $this->isItemActive($child)) {
```

**Comment by dynasource** [comment]
related https://github.com/yiisoft/yii2/issues/9366

**Comment by samdark** [comment]
@PowerGamer1 done.

**Comment by samdark** [comment]
@PowerGamer1 thank you for working on it.

**Pull request merged**
