### PR TITLE
Investigating broken yii2-bootstrap unit tests

### PR DESCRIPTION
**Pull request by PowerGamer1**
This is a test, see https://github.com/yiisoft/yii2-bootstrap/pull/158#issuecomment-257965747.

### CODE REVIEW

**Comment by dynasource** [comment]
thanks for verifying. 

Like I said, higher than 2.0.7 is not possible (already checked it locally). Tests have to be updated to the 2.0.10 state in order for the tests to pass.

**Comment by PowerGamer1** [comment]
> thanks for verifying. 
Like I said, higher than 2.0.7 is not possible (already checked it locally). Tests have to be updated to the 2.0.10 state in order for the tests to pass.

You are welcome. And by the way, I just tested with `"yiisoft/yii2": "<=2.0.9"` and as you can see the tests pass too so something was broken in Yii2 2.0.10.

**Comment by dynasource** [comment]
bootstrap tests

**Comment by dynasource** [comment]
@yiisoft/core-developers, any ideas?:
* 2.0.10 breaks tests locally & travis
* 2.0.8 & 2.0.9 breaks only locally in phpstorm because of unclosing buffers (travis accepts them)
* 2.0.7 works perfectly

Should we stick to 2.0.7 or move to 2.0.9?

**Comment by samdark** [comment]
Tests should run against latest stable release of the framework. That's what extension is used with in practice.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/b8c07f6839ef5facf67ff1482e3189abf1145978 this is the commit which caused tests to fail.

**Comment by samdark** [comment]
Since it is a good fix, tests should be adjusted.

**Comment by samdark** [comment]
The buffering problem is much trickier though...

**Comment by samdark** [comment]
@PowerGamer1 tests are fixed in master now.

**Pull request closed without merging**
