### PR TITLE
Fix active status of multilevel submenu items

### PR DESCRIPTION
**Pull request by PowerGamer1**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2-bootstrap/issues/96, https://github.com/yiisoft/yii2-bootstrap/issues/157

### CODE REVIEW

**Comment by dynasource** [comment]
https://github.com/yiisoft/yii2-bootstrap/issues/157

**Comment by PowerGamer1** [comment]
@dynasource 
@cebe 
@samdark 
@klimov-paul
@SilverFire

What is going on, I have commented out ALL my changes and still get 2 failed checks on unit tests? Did someone commit unit test breaking changes into the `master` branch?

**Comment by dynasource** [comment]
@PowerGamer1, dived into it for you. I seems that the yii2-bootstrap tests are compatible till Yii 2.0.7. Have you fetched that latest commit of @cebe? He changed composer.json to:
*  "yiisoft/yii2": "~2.0.6",

**Comment by PowerGamer1** [comment]
@dynasource 

> Have you fetched that latest commit of @cebe?

Uh, well, I just navigated to `yiisoft/yii-bootstrap` repo on GitHub.com and edited the `Nav.php` directly on GitHub.com using its online in-browser editor. Afterwards created pull request (again using GitHub.com online in-browser interface). So I'd guess everything currently in `yiisoft/yii-bootstrap` repo master branch went into my clone.

As you can see from the diff of my patch all new code I added is currently commented and the tests still fail so my changes are not to blame. My guess is something in `yiisoft-yii2` repo (probably in classes such as `yii\widgets\ActiveForm` or `yii\widgets\ActiveField` that are used as base classes in `yiisoft/yii-bootstrap`) broke the `yiisoft-bootstrap` repo tests.

**Comment by dynasource** [comment]
hmmm, seems that you have https://github.com/yiisoft/yii2-bootstrap/commits/c8cd84aee0669bcaef2fa9f0613d7bf30cb7acbd

**Comment by dynasource** [comment]
Travis shows the following:


```html
<div class="form-group field-dynamicmodel-attributename">
-<label class="control-label" for="dynamicmodel-attributename">Attribute Name</label>
+<label class="control-label">Attribute Name</label>
 <input type="hidden" name="DynamicModel[attributeName]" value=""><div id="dynamicmodel-attributename"><div class="radio"><label><input type="radio" name="DynamicModel[attributeName]" value="1"> name1</label></div>
 <div class="radio"><label><input type="radio" name="DynamicModel[attributeName]" value="2"> name2</label></div></div>
 
 <p class="help-block help-block-error"></p>
 </div>
```

```html
<div class="form-group field-dynamicmodel-attributename">
-<label class="control-label" for="dynamicmodel-attributename">Attribute Name</label>
+<label class="control-label">Attribute Name</label>
 <input type="hidden" name="DynamicModel[attributeName]" value=""><div id="dynamicmodel-attributename"><div class="checkbox"><label><input type="checkbox" name="DynamicModel[attributeName][]" value="1"> name1</label></div>
 <div class="checkbox"><label><input type="checkbox" name="DynamicModel[attributeName][]" value="2"> name2</label></div></div>
 
 <p class="help-block help-block-error"></p>
 </div>
```

seems a changed name: DynamicModel[attributeName][]

**Comment by dynasource** [comment]
ahh...I see it in the travis logs (you have to zoom for it though):

  - Installing yiisoft/yii2 (2.0.10)
    Loading from cache

This is shouldnt be happening.

**Comment by PowerGamer1** [comment]
> •Installing yiisoft/yii2 (2.0.10) Loading from cache
This is shouldnt be happening.

Why not? I think latest `master` branch of `yiisoft-bootstrap` and latest `master` branch of `yiisoft-yii2` should be compatible with each other.

**Comment by dynasource** [comment]
@PowerGamer1, can you make a change to composer.json and try again:
* "yiisoft/yii2": "<=2.0.7",

**Comment by PowerGamer1** [comment]
> @PowerGamer1, can you make a change to composer.json and try again:
•"yiisoft/yii2": "<=2.0.7",

I think experiments such as that should be conducted outside of this particular pull request. Besides, next `yii2-boostrap` release should definitely work with Yii2 2.0.10 release and future 2.0.11 version (otherwise a user won't be able to install latest version of `yii2` if he wants to install latest version of `yii2-bootstrap` which is stupid). So either a code in `yii2` responsible for breaking `yii2-bootstrap` tests should be fixed or the tests in `yii2-bootstrap` should be changed to correspond to the changes in `yii2`.

**Comment by dynasource** [comment]
alright, lets put it this way ;), would you be so kind to check if "yiisoft/yii2": "<=2.0.7" solves your PR

**Comment by PowerGamer1** [comment]
> alright, lets put it this way ;), would you be so kind to check if "yiisoft/yii2": "<=2.0.7" solves your PR

Well, since you asked nicely... I checked it in https://github.com/yiisoft/yii2-bootstrap/pull/159 and with `"yiisoft/yii2": "<=2.0.7"` the tests pass but with `"yiisoft/yii2": "~2.0.6",` (as it is currently in `master` branch) tests fail.

Still I don't understand what was the point of that check and why you couldn't do it yourself.

**Comment by dynasource** [comment]
simple. An optimal process. You are already working on that PR, so its easy for you to change composer.json.

**Comment by PowerGamer1** [comment]
Let me know please when the issue with failing unit tests on `master` branch is resolved so I can uncomment the actual code changes in my pull request.

**Comment by PowerGamer1** [comment]
Ok, my pull request is ready now, by please note that I will not be providing any unit tests for it. If you think they are needed you will have to make them on your own.

**Comment by dynasource** [comment]
these are required to prevent BC breaks in the future

**Comment by PowerGamer1** [comment]
@dynasource 
> these are required to prevent BC breaks in the future

I know what unit tests are for I just never do them (and frankly I already spent more time on this PR then I could afford).

**Comment by samdark** [comment]
OK. We'll handle tests. Will take extra time before merge though...

**Comment by samdark** [comment]
Moved into https://github.com/yiisoft/yii2-bootstrap/pull/161

**Pull request closed without merging**
