### PR TITLE
update .github folder link

### PR DESCRIPTION
**Pull request by Arhell**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |  resolve https://github.com/yiisoft/yii2-bootstrap/issues/267

### CODE REVIEW

**Comment by bizley** [comment]
This page seems to not exist.

**Comment by Arhell** [comment]
> This page seems to not exist.

remove?

**Comment by bizley** [comment]
Maybe this https://forum.yiiframework.com/c/yii-2-0/general-discussions/16 will be better instead.

**Review by Arhell — COMMENTED** [review]
@bizley  done, thanks

**Pull request merged**
