### PR TITLE
Add icons support to bootstrap widgets.

### PR DESCRIPTION
**Pull request by nkovacs**
See https://github.com/yiisoft/yii2/pull/5208 for previous discussion.

### CODE REVIEW

**Comment by nkovacs** [comment]
An advantage of the icon widget I wrote is that you can use [dependency injection](http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#practical-usage) to change its default options or even the class. So you don't have to touch your views, you only need to do this: `Yii::$container->set('yii\bootstrap\Icon', 'app\widgets\MyIcon')`.

**Comment by klimov-paul** [comment]
Closed in favour #34

**Comment by nkovacs** [comment]
That doesn't really fix the issue. The widgets still don't support icons. You still have to concatenate the icon with the label yourself, you have to disable encoding, you have to then manually encode the text part of the label.

**Comment by klimov-paul** [comment]
I rely on @crisu83's opinion at this matter:
https://github.com/yiisoft/yii2-bootstrap/pull/31#issuecomment-94781554

**Pull request closed without merging**
