### PR TITLE
Add buttons array option visible. Reference initial: bootstrap\ButtonGro...

### PR DESCRIPTION
**Pull request by lukBarros**
...up buttons 'visible' property #2546 - yiisoft/yii2#2546

This allows for dynamic way to say that an item is not shown without having to involve him with a  ''if { button }'', just pass the word you would use if as the parameter to the visible property.

Implementation was standard used in nav widget.

### CODE REVIEW

**Comment by lukBarros** [comment]
@samdark  consegui!

**Comment by pana1990** [comment]
it not workign wheter visible is true beacuse button class have not visible property.

I think that button should be visible property for it check if render button html or empty string.

For example the following code : 

new property : 

```php
/**
* @var boolean whether the button should be rendering.
* @since 2.0.4
*/
public $visible = true;
```

new behavior : 

```php
/**
* Renders the widget.
*/
public function run()
{
    if ($this->visible) {
        $this->registerPlugin('button');
        return Html::tag($this->tagName, $this->encodeLabel ? Html::encode($this->label) : $this->label, $this->options);
    } else {
        return '';
    }
}
```

@samdark @lukBarros  what do you think about it?

**Comment by lukBarros** [comment]
Ok, what you proponhe not have the visibility option in the button group widget, but the button widget in itself (smallest unit - cell).

It seems to me it makes more sense, including the same lófica applies, instead of if (expression) {button } would be the last expression as pro field visible widget button response.

Bravo!!! It seems rather to be the best place, it makes total sense!

**Comment by lukBarros** [comment]
@samdark what do you think of that?

**Comment by samdark** [comment]
While @pana1990 way of fixing it will cover more widgets I'm not sure if it makes sense to add `visible` to the button class since in case of button it's better to be handle with a simple `if` in the template. Same about `ButtonDropdown`.

I think it should be `ButtonGroup` specific.

**Comment by pana1990** [comment]
@samdark you right

@lukBarros you may use unset($button['visible']) for fix break function whether visible is true.

**Comment by samdark** [comment]
Fixed with https://github.com/yiisoft/yii2-bootstrap/commit/8e26e127447459d63a1a19a597a984403d285043. Thanks for looking into it.

**Comment by lukBarros** [comment]
Não entendi, a mudança será aceita e saíra na 2.0.4?

**Comment by pana1990** [comment]
please, Can you write the question in English?

**Comment by samdark** [comment]
@lukBarros https://github.com/yiisoft/yii2-bootstrap/commit/8e26e127447459d63a1a19a597a984403d285043 is what will be released in 2.0.4.

**Pull request closed without merging**
