### PR TITLE
removed bower constraints, upgraded yii requirement

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | ?

Detailed description will follow in https://github.com/yiisoft/yii2/issues/8452

### CODE REVIEW

**Comment by cebe** [comment]
I do not think there is any reason to remove the assets from packages that need them. yii2-bootstrap requires bootstrap css and js so it should require the asset package. Making Yii2.1 independent of assets only means that the core framework can be used without it. It does not mean that bootstrap should be able to work without it.

**Comment by schmunk42** [comment]
@cebe I've added a `packages.json` file, which could be used by `foxypkg` or via a manual installation.

**Comment by klimov-paul** [comment]
For the `yii2-bootstrap` mandatory requirement for `bootsrap` CSS should be removed. It can be mentioned at `suggets` section instead.
In practical usage most of the developers will re-asseble Bootstrap CSS from its source *.less or *.sass files - it is unlikely default compiled CSS will be in use.
Manipulating of the source files under the 'vendor' directory outside of VCS scope can not be performed, thus developer likely place Boostrap source somewhere inside his application.

**Comment by schmunk42** [comment]
> For the yii2-bootstrap mandatory requirement for bootsrap CSS should be removed. It can be mentioned at suggets section instead.

But `suggests` would still be a composer (cap) package then, it's better to move them into `packages.json`. It doesn't sound right to me, that bootstrap is not a requirement if yii2-bootstrap.

> In practical usage most of the developers will re-asseble Bootstrap CSS from its source *.less or *.sass files - it is unlikely default compiled CSS will be in use.

We're using various approaches for this, sometimes using the default css and including another file. Sometimes using the default less/sass files and recompile them with customized changes in separate files. We hardly ever touch the bootstrap core classes at all.

**Comment by klimov-paul** [comment]
> We're using various approaches for this, sometimes using the default css and including another file. Sometimes using the default less/sass files and recompile them with customized changes in separate files. We hardly ever touch the bootstrap core classes at all.

Using mandatory dependency means that someone compiling CSS from source have to install garbage Bower/Npm package - he will alreay have the Bootstrap source inside his project and have to waste time and network resources to get it from the Bower/Npm as well.

> But suggests would still be a composer (cap) package then, it's better to move them into packages.json

'Suggest' section can mention any package even not-existing one. Developer likely to notice 'sugget'  from composer installation then searching of 'peer-dependencies' inside 'package.json', which he can be unaware of.
Also 'asset-packagegist' still can be used for asset retriving.

**Comment by schmunk42** [comment]
> Using mandatory dependency means that someone compiling CSS from source have to install garbage Bower/Npm package - he will alreay have the Bootstrap source inside his project and have to waste time and network resources to get it from the Bower/Npm as well.

Why should someone have these resources already in their project?! The idea would be to get the source only once from npm (bower is deprecated) - or to install them manually.
Bootstrap is a special case, because it is available through composer, but that's an exception.

> Developer likely to notice 'sugget' from composer installation then searching of 'peer-dependencies' inside 'package.json', which he can be unaware of.

From my experience most developers don't notice either :)

> Also 'asset-packagegist' still can be used for asset retriving.

But it should be optional, I currently see no way how to do that with the way that `ap` works (specifying dependencies in `composer.json` as `asset-something`).

**Comment by samdark** [comment]
Should not be merged into version that is compatible with Yii 2.0.x.

**Comment by klimov-paul** [comment]
For the 2.2 the best solution will be usage of the native composer package for bootstrap source:
https://packagist.org/packages/twbs/bootstrap

Then dependency of `yiisoft/yii2-jquery` should be made optional.
Thus this repo will not require any plugin or NPM setup to be used.

**Comment by samdark** [comment]
I don't think so. There are tons of bootstrap themes installable via npm/bower that require bootstrap and that do not have composer.json.

**Comment by klimov-paul** [comment]
If we going to drop automatic npm/bower package installation, what is the difference?
If you do not want to install Bootstrap from composer you can add "replace" for its package, like it is described in the [docs](https://github.com/yiisoft/yii2-bootstrap/blame/2.2/docs/guide/assets-setup.md#L92-L95).

**Comment by schmunk42** [comment]
I'd rather add it if you want automatic installation.

If every package which require assets would do it like this, you'd need to look them all up and replace them manually.

**Pull request closed without merging**
