### PR TITLE
Fix: get item container from config

### PR DESCRIPTION
**Pull request by arturf**
This documented but not working

### CODE REVIEW

**Comment by samdark** [comment]
What's documented exactly?

**Comment by samdark** [comment]
Is it possible to create a unit test for it

**Comment by arturf** [comment]
Here - https://github.com/yiisoft/yii2-bootstrap/blob/master/Tabs.php#L82

**Comment by cebe** [comment]
> Here - https://github.com/yiisoft/yii2-bootstrap/blob/master/Tabs.php#L82

Looks good to me, could you add a test case and a changelog line?

**Comment by arturf** [comment]
@samdark @cebe  +

**Comment by cebe** [comment]
Merged, thank you!

**Pull request closed without merging**
