### PR TITLE
[Fixes #68] Fixed handling empty items in Nav

### LINKED ISSUE #68: yii\bootstrap\Nav makes dropdown for sub items even if there is no subitems
Code in view
```code
<?= \yii\bootstrap\Nav::widget([
            'items' => $this->context->menu
        ]); ?>

```

menu:
``` code
[
    0 => [
        'label' => 'Test'
        'url' => '/portalpage/page/default?user_id=13&id=1'
        'items' => []
        'options' => [
            'class' => 'menu-item'
            'target' => '_self'
        ]
    ]
    1 => [
        'label' => 'Ð—Ð° Ð½Ð°Ñ'
        'url' => '/portalpage/page/default?user_id=13&id=2'
        'items' => []
        'options' => [
            'class' => 'menu-item'
            'target' => '_self'
        ]
    ]
]
```
HTML
```html

<ul id="w2" class="nav">
<li class="menu-item dropdown open" target="_self"><a class="dropdown-toggle" href="/portalpage/page/default?user_id=13&amp;id=1" data-toggle="dropdown" aria-expanded="true">Test <b class="caret"></b></a>
<ul id="w3" class="dropdown-menu"></ul></li>
<li class="menu-item dropdown" target="_self"><a class="dropdown-toggle" href="/portalpage/page/default?user_id=13&amp;id=2" data-toggle="dropdown">За нас <b class="caret"></b></a><ul id="w4" class="dropdown-menu"></ul></li>
</ul>
```

As you can see there are redundant dropdowns for empty subitems array

I think that in  yii\bootstrap\Nav at line 185 the code should be 
``` code
 if (is_array($items) && !empty($items)) {
...
}
```
instead of
```code
 if (is_array($items)) {
....
}
```

### PR DESCRIPTION
**Pull request by freezy-sk**

### CODE REVIEW

**Comment by freezy-sk** [comment]
Fixes #68

**Comment by samdark** [comment]
@bashibozuk does it solve your issue?

**Comment by bashibozuk** [comment]
Well, I think, that it will work, but it would be better if you use my
proposal for the fix, I think that its much less code and much cleaner.

Best Regards, Vasil

2015-08-12 18:59 GMT+03:00 Alexander Makarov <notifications@github.com>:

**Comment by freezy-sk** [comment]
@bashibozuk with your proposal you means this?
```
if (is_array($items) && !empty($items)) {
...
}
```

**Comment by bashibozuk** [comment]
I think that the whole code from line 179 to line 197 should look like this
```php
	if (is_array($items) && !empty($items)) {
            $linkOptions['data-toggle'] = 'dropdown';
            Html::addCssClass($options, ['widget' => 'dropdown']);
            Html::addCssClass($linkOptions, ['widget' => 'dropdown-toggle']);
            if ($this->dropDownCaret !== '') {
                $label .= ' ' . $this->dropDownCaret;
            }
            
	    if ($this->activateItems) {
	        $items = $this->isChildActive($items, $active);
	    }
	    $items = $this->renderDropdown($items, $item);
            
        } else  {
	   $items = '';
	}

```

I think that looks much cleaner and you almost don't have if statement inside if statement which I hate :), but nevermind , I think that it should work your way too , but in case where you have not empty string for items instead of not empty array you will put the css classes for the dropdown and you will concatenate  the carret to the label, but still you will not render a submenu, so probably you will end with incorrect visualisation again.

**Comment by freezy-sk** [comment]
@bashibozuk I think there should be strict checking and throw an exception if items are not null and not an array, but I can break some wrongly configured applications

**Comment by klimov-paul** [comment]
Merged with adjustments 1603a2b028a83586cf1988dec741bd3e379a67f4
Thank you.

**Pull request merged**
