### PR TITLE
Bootstrap 4

### PR DESCRIPTION
**Pull request by alanwillms**
**This is a work in progress.**

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #77

### CODE REVIEW

**Comment by alanwillms** [comment]
FYI after this I will have to fix a few other places too: for example, application templates, Gii and GridView use CSS classes that no longer exist in BS4.

**Comment by cebe** [comment]
lets get the extension ready first, whether or when we will upgrade applications and gii/debug will be decided later and I'd wait for a stable boostrap release for that.

**Comment by alanwillms** [comment]
All widgets have been converted, now we just have to wait for a stable BS4 release.

As soon as I have free time I will write new tests to improve test coverage.

@cebe Bootstrap 4 requires Tether. I have included it as a composer dependency and created a `TetherAsset` class for it. Do you think this is the best approach to solve the problem?

**Comment by samdark** [comment]
Introducing extra asset bundle is OK. @cebe I think it's a good idea to create a branch now before Bootstrap 4 is released.

**Comment by alanwillms** [comment]
I will document here every point where I had to adjust some other class to work with this branch:

* Application templates:
 * [Yii basic application template](https://github.com/yiisoft/yii2-app-basic) views must be converted to BS4
* Grid
 * [yii\grid\DataColumn::$filterInputOptions](https://github.com/yiisoft/yii2/blob/master/framework/grid/DataColumn.php#L108) to `c-select` when using drop down filters
* Pagination
 * [yii\widgets\LinkPager::renderPageButtons()](https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php#L197) the `ul` must be wrapped by a `nav`
 * [yii\widgets\LinkPager::renderPageButton()](https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php#L212) `li` must have `page-item` class
 * [yii\widgets\LinkPager::renderPageButton()](https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php#L219) disabled pages must use `a` instead of `span`
 * [yii\widgets\LinkPager::renderPageButton()](https://github.com/yiisoft/yii2/blob/master/framework/widgets/LinkPager.php#L221) `a` must have `page-link` class

**Comment by samdark** [comment]
If we're talking about extension only, is it ready to be merged?

**Comment by alanwillms** [comment]
@samdark This PR is ready. I forgot to remove "WIP" from the title.

**Comment by webdevsega** [comment]
@samdark What about a new branch?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-bootstrap/tree/2.1

**Comment by cebe** [comment]
@alanwillms can you open the PR against the 2.1 branch?

**Comment by alanwillms** [comment]
@cebe done: #133

**Pull request closed without merging**
