### PR TITLE
Upgrade Bootstrap to 4.0.0.alpha2

### PR DESCRIPTION
**Pull request by alanwillms**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #77

(See original PR discussion at #125)

### CODE REVIEW

**Comment by SilverFire** [comment]
Wow! Thank you!

**Comment by alanwillms** [comment]
@SilverFire @cebe @samdark Can I open PRs targeting Gii, `LinkPager`, application templates, etc. in order to fix issues with BS4 or is it too soon?

**Comment by samdark** [comment]
You can work on it certainly.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-gii/tree/2.1

**Pull request merged**
