### PR TITLE
Added Card widget

### PR DESCRIPTION
**Pull request by grd16**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  | 

In Bootstrap 4 cards replace old panels, wells, and thumbnails - [link](https://v4-alpha.getbootstrap.com/components/card/). So I thought that it would be nice to have a Card widget.

### CODE REVIEW

**Comment by samdark** [comment]
Thanks for contribution. I'm looking at cards and not seeing much profit in having a widget for these. HTML used is very plain, no special logic so maybe it's a good idea to use it as HTML.

**Comment by grd16** [comment]
After Card I planning to create CardView (for card groups / decks / columns) widget that will extends ListView functionality. I guess that in this case separate Card widget will provide simplest and html less "mapping" cards to models. 

Pinterest like or card walls is trending in UI/UX, thats why I suggest that cards functionality need to be in yii2-bootstrap. @samdark How do you think?

**Comment by samdark** [comment]
HTML less is not the goal. We're generally adding widgets only if HTML generation is dynamic or complicated.

**Comment by samdark** [comment]
ListView with custom template would achieve that easily, I think.

**Comment by grd16** [comment]
I think that card columns will be frequently used and "custom template" is questionable approach. But I have to agree with you, considering the fact that yii2-bootstrap uses minimalism as a way to covering Bootstrap features.

**Comment by samdark** [comment]
Thanks for contribution anyway. Hope next time pull request will fit framework well.

**Comment by grd16** [comment]
No doubt! Thnx for review.

**Pull request closed without merging**
