### PR TITLE
Fixes #17016: Upgraded Twitter Bootstrap to 3.4.x

### PR DESCRIPTION
**Pull request by leoshtika**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17016

Upgrade Twitter Bootstrap from 3.3 to 3.4
Among other fixes it resolves an XSS issue in Alert, Carousel, Collapse, Dropdown, Modal, and Tab components. See https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/ & https://snyk.io/vuln/npm:bootstrap:20160627 for details.

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by looqmaan** [comment]
Hi,

May I ask when 2.0.9 will be available in composer update?

Thanks.

**Comment by machour** [comment]
@looqmaan [2.0.9](https://github.com/yiisoft/yii2-bootstrap/releases/tag/2.0.9) was just published, enjoy!

**Comment by looqmaan** [comment]
Thanks a lot, @machour.

**Pull request merged**
