### PR TITLE
Added support for the glypicons in the widgets

### PR DESCRIPTION
**Pull request by klimov-paul**
Fix for https://github.com/yiisoft/yii2/issues/5207
Added support for the glypicons in the widgets

### CODE REVIEW

**Comment by klimov-paul** [comment]
Added ability to specify icon as HTML.

**Comment by klimov-paul** [comment]
This one is more end-user friendly then #32, but affects widget internal label composition logic.

**Comment by samdark** [comment]
What if I want icons after labels?

**Comment by klimov-paul** [comment]
Yes, this is one of the problems.
The best way whould be allowing to specify `label` as an array, which can contain 'icon', 'encode' and 'template' options. But this will be inconsistent with existing `encodeLabel` and `encodeLabels` properties.

**Comment by klimov-paul** [comment]
For example:

```php
echo Button::widget([
    'label' => ['ok-sign', 'Approve'],
]);
// or
echo Button::widget([
    'label' => [
        'icon' => 'ok-sign',
        'label' => '<b>Approve</b>',
        'encode' => false,
    ],
]);
```

**Comment by klimov-paul** [comment]
It whould be nice to hear @crisu83 opinion on this matter.

**Comment by crisu83** [comment]
Lately I've become more and more convinced that while this kind of logic is kind of nice to have, a more simple and better alternative would be to have the user to add the icon in the label itself (through an icon helper of course). An example of this approach would be:

```php
yii\bootstrap\Html::icon('ok-sign') . ' <b>Approve</b>'
```

**Comment by Borales** [comment]
@klimov-paul I'm on the side of @crisu83 
Additionally to this, left position of the icon is hard-coded.
I think @crisu83's solution is more convenient

**Comment by klimov-paul** [comment]
Then what about #32 ? Is that what you whant?

**Comment by Borales** [comment]
@klimov-paul #32 - what if I would like to use other set of icons (e.g. font-awesome or ionicons)? This way - I will be forced to extend the base `Icon` class and hard-code another css-class, right?
Maybe, we could "choose" between different sets with the second parameter?

Like
```
yii\bootstrap\Html::icon('ok-sign') // by default = glyphicon
yii\bootstrap\Html::icon('ok-sign', ['class' => 'fa fa-']) // for font-awesome
// or event just
yii\bootstrap\Html::icon('ok-sign', ['class' => 'fa']) // almost all icon sets work like "setname setname-"
```

This is just a suggestion.

**Comment by klimov-paul** [comment]
You ARE able to do so. See the unit tests.

**Comment by Borales** [comment]
@klimov-paul sorry, didn't noticed that case.

**Comment by samdark** [comment]
I'm for #32. Much more flexible.

**Comment by klimov-paul** [comment]
Closed in favour #34

**Pull request closed without merging**
