### PR TITLE
Upgrade Bootstrap to 4.0.0.alpha6

### PR DESCRIPTION
**Pull request by daixianceng**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

Upgrade Bootstrap to 4.0.0.alpha6

### CODE REVIEW

**Comment by samdark** [comment]
Tests seems to be failing: https://travis-ci.org/yiisoft/yii2-bootstrap/jobs/221360374

**Comment by daixianceng** [comment]
It seems to be upgrading the unit test to bootstrap 4

**Comment by daixianceng** [comment]
Hi, it has an error "Class 'PHPUnit_Framework_TestCase' not found" in php 7. How to fix it ? https://travis-ci.org/yiisoft/yii2-bootstrap/jobs/222522627

**Comment by samdark** [comment]
It's not connected...

**Pull request closed without merging**
